                                                    ** Feature_extraction_of_Text_data_using_Tf_idf_Vectorizer**

About the Dataset:

id: unique id for a news article
title: the title of a news article
author: author of the news article
text: the text of the article; could be incomplete
label: a label that marks whether the news article is real or fake: 1: Fake news 0: real News

In [ ]:
import numpy as np
import pandas as pd
import re   #(Regular exp) Removing special characters, numbers ,Pattern matching
from nltk.corpus import stopwords   #words that don’t add much meaning(the , is)
from nltk.stem.porter import PorterStemmer  #reduces words to their root form.(running->run)
from sklearn.feature_extraction.text import TfidfVectorizer #Used to convert text into numerical feature vectors using:(TF-IDF)

In [ ]:
import nltk
nltk.download('stopwords')   #downloading dataset

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
# printing the stopwords in English
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

Stemming:

In [ ]:
port_stem = PorterStemmer()

In [ ]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content
                       if not word in stopwords.words('english')] #Remove common meaningless words
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

better to write as:
stop_words = set(stopwords.words('english'))

stemmed_content = [port_stem.stem(word)
                   for word in stemmed_content
                   if word not in stop_words]

In [ ]:
news_dataset['content'] = news_dataset['content'].apply(stemming)

KeyError: 'content'

In [ ]:
url=https://github.com/Adarshpandey-007/Indian-News-Dataset/blob/main/indian_news_dataset.csv

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (ipython-input-1672771698.py, line 1)

In [ ]:
url = "https://raw.githubusercontent.com/Adarshpandey-007/Indian-News-Dataset/main/indian_news_dataset.csv"
news_dataset = pd.read_csv(url)
news_dataset.head()

,id,title,date,category,source,url
0,1,Election Commission to hold CEOs' conference o...,2025-09-07,Politics,The Indian Express,https://indianexpress.com/article/india/electi...
1,2,International.(Open in new tab),2025-09-07,Politics,The Indian Express,https://indianexpress.com/international/
2,3,Health & Wellness,2025-09-07,Politics,The Indian Express,https://indianexpress.com/section/health-welln...
3,4,Tripura’s ruling coalition at a crossroads as ...,2025-09-07,Politics,The Indian Express,https://indianexpress.com/article/political-pu...
4,5,"With new Foreigners Act rules notified, why BJ...",2025-09-07,Politics,The Indian Express,https://indianexpress.com/article/political-pu...

In [ ]:
news_dataset['category'] = news_dataset['category'].apply(stemming)

internally it does something like:
for each_row in content_column:
    stemming(each_row)

In [ ]:
print(news_dataset['category'])

0           polit
1           polit
2           polit
3           polit
4           polit
          ...
1810    technolog
1811    technolog
1812       cultur
1813       cultur
1814       cultur
Name: category, Length: 1815, dtype: object

In [ ]:
X = news_dataset['category'].values
Y = news_dataset['source'].values
#Separating data and label

1. Select the content column from the dataset → contains the input text.
2. Convert the column to a NumPy array using .values → this becomes X, the feature set.
3. Select the label column from the dataset → contains the target classes (e.g., fake or real).
4. Convert the label column to a NumPy array using .values → this becomes Y, the target variable.
5. Now X holds all text data and Y holds corresponding labels, ready for ML model input.

In [ ]:
print(X)

['polit' 'polit' 'polit' ... 'cultur' 'cultur' 'cultur']

In [ ]:
Y.shape

(1815,)

In [ ]:
# convert the textual data to Feature Vectors
vectorizer = TfidfVectorizer()

In [ ]:
vectorizer.fit(X)

X = vectorizer.transform(X)

**vectorizer.fit(X)**
X is your array of cleaned text documents.
.fit() learns the vocabulary from all documents in X.
It calculates term frequencies (or TF-IDF values if using TfidfVectorizer).
This does not yet convert text to numbers; it only builds the internal mapping of words → feature indices.
**ex:**If X contains:["break news market", "polit debate heat"]
Vocabulary learned might be:["break", "news", "market", "polit", "debate", "heat"]

**X = vectorizer.transform(X)**
Converts each text document in X into a numerical vector.
Each vector shows the TF-IDF score (or count) of each word in the vocabulary.
The result is a sparse matrix of shape (num_documents, num_features).
**Example:**
Text → Vector:
"break news market" → [1, 1, 1, 0, 0, 0]
"polit debate heat" → [0, 0, 0, 1, 1, 1]

.fit() → learns vocabulary and statistics (TF, IDF, etc.)

.transform() → applies the learned vocabulary to convert text into numbers

In [ ]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2174 stored elements and shape (1815, 10)>
  Coords	Values
  (0, 6)	1.0
  (1, 6)	1.0
  (2, 6)	1.0
  (3, 6)	1.0
  (4, 6)	1.0
  (5, 6)	1.0
  (6, 6)	1.0
  (7, 6)	1.0
  (8, 6)	1.0
  (9, 6)	1.0
  (10, 6)	1.0
  (11, 6)	1.0
  (12, 6)	1.0
  (13, 6)	1.0
  (14, 6)	1.0
  (15, 6)	1.0
  (16, 6)	1.0
  (17, 6)	1.0
  (18, 6)	1.0
  (19, 6)	1.0
  (20, 6)	1.0
  (21, 6)	1.0
  (22, 6)	1.0
  (23, 6)	1.0
  (24, 6)	1.0
  :	:
  (1790, 9)	1.0
  (1791, 9)	1.0
  (1792, 9)	1.0
  (1793, 9)	1.0
  (1794, 9)	1.0
  (1795, 9)	1.0
  (1796, 9)	1.0
  (1797, 9)	1.0
  (1798, 9)	1.0
  (1799, 9)	1.0
  (1800, 9)	1.0
  (1801, 9)	1.0
  (1802, 9)	1.0
  (1803, 9)	1.0
  (1804, 9)	1.0
  (1805, 9)	1.0
  (1806, 9)	1.0
  (1807, 9)	1.0
  (1808, 9)	1.0
  (1809, 9)	1.0
  (1810, 9)	1.0
  (1811, 9)	1.0
  (1812, 1)	1.0
  (1813, 1)	1.0
  (1814, 1)	1.0

 ***Numerical_Dataset_Pre_Processing_Use_Case\***

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

https://github.com/plotly/datasets/blob/master/diabetes.csv  changed to below link

In [ ]:
url = "https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv"
df = pd.read_csv(url)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
X = df.drop(columns='Outcome', axis =1)
Y = df['Outcome']
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [ ]:
scaler = StandardScaler()

In [ ]:
standardized_data = scaler.fit_transform(X)

In [ ]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [ ]:
X = standardized_data

In [ ]:
#Splitting the dataset into Training data & Testing Data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)


print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)